/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData writing = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData survey = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData review = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData architecture_and_city = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData askcom = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogwheel = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData communications = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computing = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData domain = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData interface = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logotype = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shapes_and_symbols = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transportation__1_ = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tool = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transportation = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
